### ISSUE TITLE
Plugin Crashes wp-admin not site

### ISSUE THREAD

**Issue by gkarmas** [RocketChat/WordPressPlugin#10]
On a fresh WP installation:

```
13594#0: *67414 FastCGI sent in stderr: "PHP message: PHP Fatal error: Uncaught Error: Call to undefined method RocketChat_LIVEChat::_process_formData() in /var/www/vhosts/mydomain.com/httpdocs/wp-content/plugins/livechat-wordpress/livechat-wordpress.php:340
Stack trace:
#0 /var/www/vhosts/mydomain.com/httpdocs/wp-includes/plugin.php(525): RocketChat_LIVEChat->rocketchat_livechat_admin_init('')
#1 /var/www/vhosts/mydomain.com/httpdocs/wp-admin/admin.php(168): do_action('admin_init')
#2 /var/www/vhosts/mydomain.com/httpdocs/wp-admin/index.php(10): require_once('/var/www/vhosts...')
#3 {main}
thrown in /var/www/vhosts/mydomain.com/httpdocs/wp-content/plugins/livechat-wordpress/livechat-wordpress.php on line 340" while reading response header from upstream
```

**Comment by engelgabriel** [comment]
@sampaiodiego can you take a look at this?

**Comment by liveitpros** [comment]
Sorry I did not notate in the readme for this that this is a prerelease plugin.  It is not functional yet.  I have been too busy lately to complete it but I see I should get back to work on it

**Comment by tikmaster** [comment]
@liveitpros yes please sir :) Much appreciated, I can help you on tests and debugging as well.

**Comment by defcon1702** [comment]
How can I get this to work?
I'm very interested in a connection between Wordpress and rocket.chat....
